// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteErrorType(arg1:string):Promise<main.TradeDashboard>;

export function DeleteJournal(arg1:string):Promise<main.TradeDashboard>;

export function DeleteTrade(arg1:string):Promise<main.TradeDashboard>;

export function ExportDataToExcel(arg1:string):Promise<string>;

export function ExportTradesToCSV(arg1:string):Promise<string>;

export function GetDashboard():Promise<main.TradeDashboard>;

export function ImportTradesFromExcel(arg1:string):Promise<main.TradeDashboard>;

export function SaveErrorType(arg1:main.ErrorTypeEntry):Promise<main.TradeDashboard>;

export function SaveJournal(arg1:main.DailyJournalEntry):Promise<main.TradeDashboard>;

export function SaveTrade(arg1:main.TradeEntry):Promise<main.TradeDashboard>;
