// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteErrorType(arg1) {
  return window['go']['main']['App']['DeleteErrorType'](arg1);
}

export function DeleteJournal(arg1) {
  return window['go']['main']['App']['DeleteJournal'](arg1);
}

export function DeleteTrade(arg1) {
  return window['go']['main']['App']['DeleteTrade'](arg1);
}

export function ExportDataToExcel(arg1) {
  return window['go']['main']['App']['ExportDataToExcel'](arg1);
}

export function ExportTradesToCSV(arg1) {
  return window['go']['main']['App']['ExportTradesToCSV'](arg1);
}

export function GetDashboard() {
  return window['go']['main']['App']['GetDashboard']();
}

export function ImportTradesFromExcel(arg1) {
  return window['go']['main']['App']['ImportTradesFromExcel'](arg1);
}

export function SaveErrorType(arg1) {
  return window['go']['main']['App']['SaveErrorType'](arg1);
}

export function SaveJournal(arg1) {
  return window['go']['main']['App']['SaveJournal'](arg1);
}

export function SaveTrade(arg1) {
  return window['go']['main']['App']['SaveTrade'](arg1);
}
